#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CONTRACT_ROOT = ROOT / "contracts" / "public" / "v1"
RELAY_ROOT = ROOT / "contracts" / "relay" / "v1"
ATTACHMENT_ROOT = ROOT / "contracts" / "attachment" / "v1"
RUST_OUTPUT = ROOT / "crates" / "owlmux-server" / "src" / "generated" / "contracts.rs"
TS_OUTPUT = ROOT / "apps" / "web" / "src" / "generated" / "contracts.ts"


def load_json(name: str, root: Path = CONTRACT_ROOT) -> dict[str, Any]:
    return json.loads((root / name).read_text(encoding="utf-8"))


def quoted(values: list[str]) -> str:
    return ", ".join(json.dumps(value) for value in values)


def rust_int(value: int) -> str:
    return f"{value:_}"


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "array":
        return f"Array<{ts_type(schema['items'])}>"
    raise ValueError(f"unsupported schema shape: {schema}")


def render_interfaces(control: dict[str, Any]) -> str:
    rendered: list[str] = []
    for name, schema in sorted(control["$defs"].items()):
        if schema.get("type") != "object" or schema.get("additionalProperties") is not False:
            raise ValueError(f"{name} must be a closed object")
        required = set(schema.get("required", []))
        fields = [
            f"  {field}{'' if field in required else '?'}: {ts_type(value)};"
            for field, value in schema["properties"].items()
        ]
        rendered.append(f"export interface {name} {{\n" + "\n".join(fields) + "\n}")
    return "\n\n".join(rendered)


def render_rust(
    manifest: dict[str, Any],
    status: dict[str, Any],
    error: dict[str, Any],
    control: dict[str, Any],
    relay_manifest: dict[str, Any],
    attachment_manifest: dict[str, Any],
) -> str:
    status_values = status["properties"]["status"]["enum"]
    error_values = error["properties"]["code"]["enum"]
    version = manifest["version"]
    control_id = control["$id"]
    return f'''// Generated by scripts/contracts/generate.py. Do not edit.\n\npub const PUBLIC_CONTRACT_VERSION: &str = {json.dumps(version)};\npub const CONTROL_SCHEMA_ID: &str = {json.dumps(control_id)};\npub const STATUS_VALUES: &[&str] = &[{quoted(status_values)}];\npub const ERROR_CODES: &[&str] = &[{quoted(error_values)}];
pub const RELAY_PROTOCOL_VERSION: u16 = {relay_manifest["protocol"]};
pub const RELAY_MAX_FRAME_BYTES: usize = {relay_manifest["max_frame_bytes"]};
pub const RELAY_MAX_DATA_BYTES: usize = {relay_manifest["max_data_bytes"]};
pub const RELAY_MAX_STREAMS: usize = {relay_manifest["max_streams"]};
pub const ATTACHMENT_CONTRACT_VERSION: &str = {json.dumps(attachment_manifest["version"])};
pub const ATTACHMENT_MAX_FRAME_BYTES: usize = {rust_int(attachment_manifest["max_frame_bytes"])};
pub const ATTACHMENT_MAX_TERMINAL_CHUNK_BYTES: usize = {rust_int(attachment_manifest["max_terminal_chunk_bytes"])};
pub const ATTACHMENT_MAX_PANES: usize = {rust_int(attachment_manifest["max_panes"])};
pub const ATTACHMENT_MAX_PANE_SNAPSHOT_BYTES: usize = {rust_int(attachment_manifest["max_pane_snapshot_bytes"])};
pub const ATTACHMENT_MAX_PROJECTION_BYTES: usize = {rust_int(attachment_manifest["max_projection_bytes"])};\n'''


def render_typescript(
    manifest: dict[str, Any],
    status: dict[str, Any],
    error: dict[str, Any],
    control: dict[str, Any],
    attachment_manifest: dict[str, Any],
) -> str:
    status_values = status["properties"]["status"]["enum"]
    stage_values = status["properties"]["stage"]["enum"]
    error_values = error["properties"]["code"]["enum"]
    status_union = " | ".join(json.dumps(value) for value in status_values)
    stage_union = " | ".join(json.dumps(value) for value in stage_values)
    error_union = " | ".join(json.dumps(value) for value in error_values)
    return f'''// Generated by scripts/contracts/generate.py. Do not edit.\n\nexport const PUBLIC_CONTRACT_VERSION = {json.dumps(manifest['version'])} as const;
export const ATTACHMENT_CONTRACT_VERSION = {json.dumps(attachment_manifest['version'])} as const;
export const ATTACHMENT_MAX_FRAME_BYTES = {attachment_manifest['max_frame_bytes']} as const;
export const ATTACHMENT_MAX_TERMINAL_CHUNK_BYTES = {attachment_manifest['max_terminal_chunk_bytes']} as const;
export const ATTACHMENT_MAX_PANES = {attachment_manifest['max_panes']} as const;
export const ATTACHMENT_MAX_PANE_SNAPSHOT_BYTES = {attachment_manifest['max_pane_snapshot_bytes']} as const;
export const ATTACHMENT_MAX_PROJECTION_BYTES = {attachment_manifest['max_projection_bytes']} as const;\nexport type ServiceStatus = {status_union};\nexport type ServiceStage = {stage_union};\nexport type ErrorCode = {error_union};\n\nexport interface BuildMetadata {{\n  id: string;\n  version: string;\n}}\n\nexport interface StatusResponse {{\n  service: "owlmux-server";\n  stage: ServiceStage;\n  status: ServiceStatus;\n  build: BuildMetadata;\n}}\n\nexport interface ErrorResponse {{\n  code: ErrorCode;\n  message: string;\n  retry_after?: number;\n}}\n\n{render_interfaces(control)}\n'''


def format_rust(content: str) -> str:
    process = subprocess.run(
        ["rustfmt", "--emit", "stdout", "--edition", "2024"],
        cwd=ROOT,
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return process.stdout


def format_typescript(content: str) -> str:
    process = subprocess.run(
        ["pnpm", "--filter", "@owlmux/web", "exec", "prettier", "--stdin-filepath", str(TS_OUTPUT)],
        cwd=ROOT,
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return process.stdout


def update(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == expected:
        return True
    if check:
        print(f"generated contract is stale: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate OwlMux contract bindings")
    parser.add_argument("--check", action="store_true", help="fail when generated files differ")
    args = parser.parse_args()

    manifest = load_json("manifest.json")
    status = load_json("status.schema.json")
    error = load_json("error.schema.json")
    control = load_json("control.schema.json")
    relay_manifest = load_json("manifest.json", RELAY_ROOT)
    relay_schema = load_json("relay.schema.json", RELAY_ROOT)
    attachment_manifest = load_json("manifest.json", ATTACHMENT_ROOT)
    attachment_schema = load_json("attachment.schema.json", ATTACHMENT_ROOT)
    if manifest.get("version") != "public.v1":
        raise ValueError("unsupported public contract version")
    if status.get("additionalProperties") is not False or error.get("additionalProperties") is not False:
        raise ValueError("public contracts must reject unknown fields")
    if sorted(manifest["schemas"]) != sorted(["control.schema.json", "error.schema.json", "status.schema.json"]):
        raise ValueError("public contract manifest is incomplete")
    if relay_manifest.get("version") != "relay.v1" or relay_manifest.get("protocol") != 1:
        raise ValueError("unsupported Relay contract version")
    if relay_manifest.get("schemas") != ["relay.schema.json"] or "$defs" not in relay_schema:
        raise ValueError("Relay contract manifest is incomplete")
    if attachment_manifest.get("version") != "attachment.v1":
        raise ValueError("unsupported attachment contract version")
    if attachment_manifest.get("schemas") != ["attachment.schema.json"] or "$defs" not in attachment_schema:
        raise ValueError("attachment contract manifest is incomplete")
    for root in (RELAY_ROOT, ATTACHMENT_ROOT):
        for fixture in (root / "fixtures").glob("*.json"):
            json.loads(fixture.read_text(encoding="utf-8"))

    rust = format_rust(
        render_rust(manifest, status, error, control, relay_manifest, attachment_manifest)
    )
    ok = update(RUST_OUTPUT, rust, args.check)
    typescript = format_typescript(
        render_typescript(manifest, status, error, control, attachment_manifest)
    )
    ok = update(TS_OUTPUT, typescript, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
